module fortgen_banner
    !! Provenance headers for generated files.
    !!
    !! Generated code that cannot be traced back to its generator becomes
    !! unmaintainable the first time somebody edits it by hand and their change
    !! is silently overwritten. The banner names the generator, says plainly not
    !! to edit the file, and records how to regenerate it.
    use fortgen_buffer, only: buffer_t
    implicit none
    private

    public :: put_banner

contains

    subroutine put_banner(b, generator, regenerate, note)
        !! Write a provenance header.
        type(buffer_t), intent(inout) :: b
        !! What produced this file, including its version.
        character(len=*), intent(in) :: generator
        !! The exact command that regenerates it.
        character(len=*), intent(in), optional :: regenerate
        !! An extra line, such as a licensing statement about the output.
        character(len=*), intent(in), optional :: note

        call b%line("! Generated by "//generator//". Do not edit.")
        if (present(regenerate)) then
            call b%line("!")
            call b%line("! Regenerate with:")
            call b%line("!     "//regenerate)
        end if
        if (present(note)) then
            call b%line("!")
            call b%line("! "//note)
        end if
        call b%line("")
    end subroutine put_banner

end module fortgen_banner
